# Font
bold_font        auto
italic_font      auto
font_size 19.0

#Background
foreground #ffffff
background #4f4f4f

#Cursor
cursor_text_color #3f3f3f
cursor_shape block

#Titlebar
hide_window_decorations titlebar-only

#Window size
remember_window_size

#Clipboard
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
